name: sunrise
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  build: ^2.2.1
  build_config: ^1.0.0
  source_gen: ^1.2.1
  analyzer: ^3.2.0

  sunrise_annotation:
    git:
      url: https://github.com/munitum/sunrise.git
      path: sunrise_annotation

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.1
  test: ^1.20.1
